"""create_testdata

Revision ID: 3f934e44f7e3
Revises: 7a0991cba51f
Create Date: 2026-09-25 15:52:21.788073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3f934e44f7e3'
down_revision: Union[str, None] = '7a0991cba51f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('synonyms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_fields_key'), 'domain_fields', ['key'], unique=True)
    op.create_table('column_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('header_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_column_mappings_header_fingerprint'), 'column_mappings', ['header_fingerprint'], unique=False)
    op.create_index(op.f('ix_column_mappings_owner_id'), 'column_mappings', ['owner_id'], unique=False)
    op.create_table('user_bases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('certification_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('header_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('mapping_id', sa.UUID(), nullable=True),
    sa.Column('purge_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['certification_id'], ['certifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mapping_id'], ['column_mappings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_bases_certification_id'), 'user_bases', ['certification_id'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_case_id', sa.UUID(), nullable=False),
    sa.Column('user_base_id', sa.UUID(), nullable=False),
    sa.Column('row_ref', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('justification', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('derived_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('manual_override', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_base_id'], ['user_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_test_case_id'), 'assignments', ['test_case_id'], unique=False)
    op.create_table('case_conditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_case_id', sa.UUID(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('derived_inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mutates_state', sa.Boolean(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_conditions_test_case_id'), 'case_conditions', ['test_case_id'], unique=True)
    op.create_table('data_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('certification_id', sa.UUID(), nullable=False),
    sa.Column('test_case_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['certification_id'], ['certifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_requests_certification_id'), 'data_requests', ['certification_id'], unique=False)
    # ### end Alembic commands ###

    # Seed: campos de dominio del piloto (§6.5)
    import uuid as _uuid
    from datetime import datetime, timezone
    _now = datetime.now(timezone.utc)
    _module = "novedades_afiliacion"
    _fields = [
        ("document_type",       "Tipo de documento",            "text",    ["tipo_doc", "tipo_documento"]),
        ("document_number",     "Número de documento",          "text",    ["num_doc", "cedula", "documento"]),
        ("full_name",           "Nombre completo",              "text",    ["nombre", "nombre_completo"]),
        ("contract_number",     "Número de contrato",           "text",    ["num_contrato", "contrato"]),
        ("affiliate_role",      "Tipo de afiliado",             "text",    ["tipo_afiliado", "rol"]),
        ("contract_status",     "Estado del contrato",          "text",    ["estado_contrato", "estado"]),
        ("contract_start_date", "Fecha inicio contrato",        "date",    ["fecha_inicio_contrato", "f_inicio"]),
        ("contract_end_date",   "Fecha fin contrato",           "date",    ["fecha_fin_contrato", "f_fin"]),
        ("ips_start_date",      "Fecha inicio IPS",             "date",    ["fecha_inicio_ips"]),
        ("ips_end_date",        "Fecha fin IPS",                "date",    ["fecha_fin_ips"]),
        ("contributor_type",    "Tipo de cotizante",            "text",    ["tipo_cotizante"]),
        ("has_beneficiaries",   "Tiene beneficiarios",          "boolean", ["tiene_beneficiarios"]),
        ("employer_id",         "NIT del empleador",            "text",    ["nit_empleador", "empleador"]),
        ("affiliation_date",    "Fecha de afiliación",          "date",    ["fecha_afiliacion"]),
    ]
    op.bulk_insert(
        sa.table(
            "domain_fields",
            sa.column("id", sa.UUID()),
            sa.column("key", sa.String()),
            sa.column("label", sa.String()),
            sa.column("data_type", sa.String()),
            sa.column("module", sa.String()),
            sa.column("synonyms", postgresql.JSONB()),
            sa.column("created_at", sa.DateTime(timezone=True)),
            sa.column("updated_at", sa.DateTime(timezone=True)),
        ),
        [
            {
                "id": str(_uuid.uuid4()),
                "key": key,
                "label": label,
                "data_type": dtype,
                "module": _module,
                "synonyms": synonyms,
                "created_at": _now,
                "updated_at": _now,
            }
            for key, label, dtype, synonyms in _fields
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_requests_certification_id'), table_name='data_requests')
    op.drop_table('data_requests')
    op.drop_index(op.f('ix_case_conditions_test_case_id'), table_name='case_conditions')
    op.drop_table('case_conditions')
    op.drop_index(op.f('ix_assignments_test_case_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_user_bases_certification_id'), table_name='user_bases')
    op.drop_table('user_bases')
    op.drop_index(op.f('ix_column_mappings_owner_id'), table_name='column_mappings')
    op.drop_index(op.f('ix_column_mappings_header_fingerprint'), table_name='column_mappings')
    op.drop_table('column_mappings')
    op.drop_index(op.f('ix_domain_fields_key'), table_name='domain_fields')
    op.drop_table('domain_fields')
    # ### end Alembic commands ###
